frontend/controllers/HomeController.php
<?php

namespace frontend\controllers;

use frontend\models\News;
use Yii;
use yii\db\Query;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

class HomeController extends Controller
{

    public function beforeAction($action)
    {
        if(parent::beforeAction($action)){
            if (!Yii::$app->session->get('isLoggedin')){

                Yii::$app->session->setFlash('error', "Error, please sign in to start your session.");
                
                $this->redirect(['login/index']);
                return false;
            }
            
            return true;
            
        }
    }

    public $layout = "template";
    public $title = "Profiling - Home";

    public function actionIndex()
    {
        Yii::$app->view->title = $this->title;
         // $reply = ChatReply::findOne(['unique_id_msg' => $unique_id_msg]);
        //  $news = News::findAll() ;
        $query = New Query();
        $data['news']  = $query->from('news')
                ->limit(5)
                ->all();
        
        return $this->render('index', $data);
    } 
    
    public function actionIndex_old()
    {
        Yii::$app->view->title = $this->title;
        return $this->render('index_old');
    }

    public function actionView()
    {        
        Yii::$app->view->title = $this->title;
        $input = Yii::$app->request->get();

        $id = $input['id'];

        $news = News::findOne(['news_id' => $id]);

        $data = array(
                        'news_id'      => $news['news_id'],
                        'news_title'   => $news['news_title'],
                        'news_content' => $news['news_content'],
                        'news_img'     => ($news['news_img']) ? substr($news['news_img'], strpos($news['news_img'], 'uploads')) : ''
                    );

        return $this->render('view', $data);

    }
    
}

frontend/controllers/ProfilingController.php
<?php

namespace frontend\controllers;

use app\models\McuHeader;
use app\models\MDisease;
use app\models\ProfilingDiseaseHistory;
use app\models\ProfilingHistory;
use backend\components\RestHelper;
use backend\models\UploadForm;
use frontend\models\Employee;
use frontend\models\Profiling;
use frontend\models\ProfilingDisease;
use Yii;
use yii\web\Controller;


class ProfilingController extends Controller
{
    protected $title = "Profiling";

    private $success = 'Success';
    private $failed = 'Failed';

    public function beforeAction($action)
    {
        if(parent::beforeAction($action)){
            if (!Yii::$app->session->get('isLoggedin')){

                Yii::$app->session->setFlash('error', "Error, please sign in to start your session.");
                
                $this->redirect(['login/index']);
                return false;
            }
            
            return true;
            
        }
    }

    public function actionIndex()
    {
        Yii::$app->view->title = $this->title;
       return $this->render('index');
    }
    
    public function actionCreate()
    {
        Yii::$app->view->title = $this->title;
        $data['act'] = "add";
        $list_disease = [];
        $profil = new Profiling();
        $disease_h =  $profil->getDiseaseHeader();
        foreach($disease_h as $key=>$val){
            
            $list_disease[$val['type']] = $profil->getDiseaseDetail(["type"=>$val["type"]]);
        }
           
        $data["list_disease"] = $list_disease; 
        return $this->render('create', $data);
    } 
    
    public function actionGetemployee()
    {
     
        // return $this->render('get_employee'); //get hanya view doank
        return $this->renderAjax('get_employee');
    }

    public function actionSave()
    {

        $input = Yii::$app->request->post();       
        $act = $input['act'];
        $id = $input['id'];
        $employee = $input['employee'];       
        // $diagnosa = implode(",", $input['medical_diagnosis']);
        $diagnosa = null;
        $notes = $input['notes'];
        $nik_user = Yii::$app->session->get('nik');
        $datetime = date('Y-m-d H:i:s');
        $connection = Profiling::getDb();
        $transaction = $connection->beginTransaction();
        
        try{    

            if(strtolower($act)=="add"){
                $cek = Profiling::findOne(["nik" => $employee]);
                if($cek){
                    $result = ['status' => $this->failed, 'message' => "Employee data already exists"];
                    RestHelper::send_response(200, $result ); 
                    exit;
                }
            }

            $profil = new Profiling();
            if(strtolower($act)=="add"){
                $profil->created_by = $nik_user;
                $profil->created_date = $datetime;
                $profil->created_ip = $_SERVER['REMOTE_ADDR'];
                $msg = "Successfully create data";
            } else { //update
                $profil = Profiling::findOne(["profiling_id" => $id]);
                $msg = "Successfully update data";

                //add to history    
                $this->saveHistory($employee);                  
            }
            $profil->nik = $employee;
            $profil->diagnosa = $diagnosa;
            $profil->notes = $notes;           
            $profil->updated_by = $nik_user;
            $profil->updated_date = $datetime;
            $profil->updated_ip = $_SERVER['REMOTE_ADDR'];
          
            if (isset($_FILES['file_profiling']['name']) && $_FILES['file_profiling']['name']) {
                $model = new UploadForm();
                $model->file = \yii\web\UploadedFile::getInstanceByName('file_profiling');
             
                if ($model->validate()) {                   
                    $path_dir = "profiling";
                    $upload = $model->doupload($path_dir);
                    if ($upload !== false) {
                        
                        // file gak di hapus karena buat history
                        //  if($profil['attachment']){ //hapus file sebelumnya  
                        //      $this->deleteFile($profil['attachment']);
                        //  }
                        
                        $profil->attachment = $upload['file_name'];

                        
                    }
                }
            }
           
            $profil->save();

            $prof_dis = new ProfilingDisease();
            $prof_dis->deleteAll(["nik"=>$input['employee']]);

            if($input["disease"]){
                foreach($input["disease"] as $key=>$val){
                    $dis_d = new ProfilingDisease();
                    $dis_d->nik = $input['employee'];
                    $dis_d->disease_id = $val;
                    if($val=="000"){
                        $dis_d->other = $input["other_text"];
                    }
                    $dis_d->save();
                }
            }
           
            $transaction->commit();
            $res_status = $this->success;
            $message = $msg;

        } catch (\Exception $e) {
            $transaction->rollBack();
            $res_status = $this->failed;
            if(YII_DEBUG){
                $message = $e->getMessage();
            } else{
                $message = "Failed to process data";
            }
        }
        $result = ['status' => $res_status, 'message' => $message];

        RestHelper::send_response(200, $result ); 
    }

    function saveHistory($nik) 
    {
      try{
        if($nik){
            $nik_user = Yii::$app->session->get('nik');
            $datetime = date('Y-m-d H:i:s');
            $prof = Profiling::findOne(["nik"=>$nik]);           
            $prof_his = New ProfilingHistory();    
            $prof_his->nik =  $prof["nik"];
            $prof_his->notes = $prof["notes"] ;
            $prof_his->created_by =  $prof["created_by"] ;
            $prof_his->created_date = $prof["created_date"] ;
            $prof_his->attachment = $prof["attachment"];

            $prof_his->created_by_insert =  $nik_user ;
            $prof_his->create_date_insert = $datetime ;       
            if($prof_his->save(false)) {
                $id_h = $prof_his->profiling_id_h ;
            }

            $detail = ProfilingDisease::findAll(["nik"=>$nik]);
            if($detail){
                foreach($detail as $key=>$val){
                    $dis_d = new ProfilingDiseaseHistory();
                    $dis_d->profiling_id_h = $id_h;
                    $dis_d->nik = $val["nik"];
                    $dis_d->disease_id = $val["disease_id"];
                    $name_dis = MDisease::findOne(["disease_id"=>$val["disease_id"]]);
                    $dis_d->name_disease = (isset($name_dis["name"])) ? $name_dis["name"] : null;
                    $dis_d->other = $val["other"];                
                    $dis_d->save(false);
                }
            }
            return true;
       } else {
           return false;
       }

      }catch (\Exception $e){
        if(YII_DEBUG){
            $message = $e->getMessage();
        } else{
            $message = "Failed to process data";
        }       
        return $message;
      }
    }

    public function actionList()
    {        

        $input = Yii::$app->request->post();

        $result = array("data" => array(), "draw" => 0, "recordsFiltered" => 0, "recordsTotal" => 0 );
        $rawLength      = $input["length"];
        $start          = $input["start"];
        $search         = $input["search"];
        $order          = $input["order"];
        $columns        = $input["columns"];

        $order_clm      = $columns[$order[0]["column"]]["data"];
        $order_clm      = ($order_clm=="profiling_id") ? "updated_date" : $order_clm; //set default updated_date
        $order_dir      = $order[0]["dir"];
        $order_dir      =  ($order_clm=="updated_date") ? "desc" : $order_dir; //set default desc jika order_clm updated_date
        $draw           = $input["draw"];
        $ofsite         = $rawLength;
       
        $formfilter = (isset($input["_formdata"]) && $input["_formdata"]) ? $input["_formdata"] : [];
        $data = Profiling::get_profiling_datatable( $order_clm, $order_dir, $start, $ofsite, $search["value"], $formfilter );

        $no = $start+1;
        foreach($data["rows"] as $keyVal => $value){
            $dataRaw = array();
            foreach($columns as $k => $rawCol){
                $dataRaw[$rawCol["data"]] = "";

                if(array_key_exists($rawCol["data"], $value)){
                    $row_data = $value[$rawCol["data"]];
                    if($rawCol["data"] != "no"){
                        $dataRaw[$rawCol["data"]] = $row_data;
                    }
                }
            }

            $dataRaw["no"]      = $no;
            $dataRaw["profiling_id"] = $value['profiling_id'];

            $dataRaw["profiling_group"] = $this->getProfilingDisease($value['nik']);

            array_push($result["data"], $dataRaw);
            $no++;
        }

        $result["draw"]             =  $draw;
        $result["recordsTotal"]     =  $data["num_rows"];
        $result["recordsFiltered"]  =  $data["num_rows"];

        RestHelper::send_response(200, $result);

    }

     public function actionListemployee()
    {        

        $input = Yii::$app->request->get();

        $result = array("data" => array(), "draw" => 0, "recordsFiltered" => 0, "recordsTotal" => 0 );
        $rawLength      = $input["length"];
        $start          = $input["start"];
        $search         = $input["search"];
        $order          = $input["order"];
        $columns        = $input["columns"];

        $order_clm      = $columns[$order[0]["column"]]["data"];
        $order_dir      = $order[0]["dir"];
        $draw           = $input["draw"];
        $ofsite         = $rawLength;

frontend/views/profiling/create.php
<?php 

use abei2017\emoji\Emoji;
use yii\helpers\Url;
use yii\web\View;
use common\components\Helper;

$type_dis = (isset($act) && $act=="update") ? "Update" : "Create";

?>

	<!-- bootstrap wysihtml5 - text editor -->
	<?php $this->registerCssFile('@web/assets/vendor_plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.css'); ?>

  <?php $this->registerCssFile('@web/assets/vendor_components/bootstrap-select/dist/css/bootstrap-select.css'); ?>
	<?php $this->registerCssFile('@web/assets/vendor_components/select2/dist/css/select2.min.css'); ?>
	<?php $this->registerCssFile('@web/assets/vendor_components/sweetalert/sweetalert.css'); ?>
	<?php $this->registerCssFile('@web/css/custom.css'); ?>



  <!-- Content Wrapper. Contains page content -->
  <!-- <div class="content-wrapper"> -->
    <!-- Content Header (Page header) -->
   <div class="content-header" style="padding-top:60px !important">
    <div class="d-flex align-items-center">
      <div class="mr-auto">
        <h3 class="page-title"><?= $this->title ?></h3>
        <div class="d-inline-block align-items-center">
          <nav>
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="<?= Url::base() . "/home/index" ?>"><i class="mdi mdi-home-outline"></i></a></li>
              <li class="breadcrumb-item"><a href="<?= Url::base() . "/profiling" ?> ">List Profiling</a></li>
              <li class="breadcrumb-item active" aria-current="page"><?= $type_dis ?> Profiling</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>  

    <!-- Main content -->
    <section class="content" style="padding-top:20px !important">
      <div class="row">
        <div class="col-12">          
          
            

          <div class="box">
            <div class="box-header">
              <h4 class="box-title"><?= $type_dis ?> Profiling<br>               
              </h4>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <form id="profiling_form" role="form">
                <div class="form-group">
                  <label>Employee</label>
                  <div class="input-group">
                    <input type="text" class="form-control" id="name_employee" name="name_employee" value="<?= isset($emp['nama']) ? $emp['nama'] : "" ?>" placeholder="Search..." readonly >
                    <input type="hidden" id="employee_h" name="employee" value="<?= isset($data['nik']) ? $data['nik'] : "" ?>" >
                    <span class="input-group-btn">
                      <?php if($act=="add"){ ?>
                      <button type="button" class="btn btn-info dialog-modal" data-url="<?= Url::base() ?>/profiling/getemployee" data-title="List Employee"><i class="fa fa-search" aria-hidden="true"></i></button>
                      <?php } ?>
                    </span>
                  </div>
                  <input type="hidden" id="act" name="act" value="<?= $act ?>">
                  <input type="hidden" id="id" name="id" value="<?= isset($id) ? $id : "" ?>">       
                </div>
               
                <div class="form-group">
                  <label>File</label>
                  <div class="controls">
                    <input type="file" name="file_profiling" id="file_profiling" class="form-control" accept=".jpg,.png,.doc,.docx,.pdf"aria-invalid="false"> <div class="help-block"></div>
                  <?php
                    if(isset($data['attachment']) && $data['attachment']){ ?>
                    <a href="<?= "/profiling/download?file=".$data['attachment'] ?>" target="_blank"><?= $data['attachment'] ?></a>
                  <?php  }
                  ?>
                  <small>Size Max : 5mb, Type : doc, docx, pdf, jpg, jpeg, png</small>
                  </div>
                </div>
                   
                <div class="form-group">
                  <label>Notes</label>
                  <textarea id="notes" name="notes" class="form-control col-lg-12" placeholder="Place some text here" ><?= isset($data['notes']) ? $data['notes'] : "" ?></textarea>
                </div>

                <div class="form-group">
                  <label>Profiling</label>                                    
                  <?php
                    $no=1;
                    foreach($list_disease as $label=>$val){  ?>
                       <div class="col-lg-2"><strong><?= ucwords(str_replace("_"," ", $label)) ?></strong></div>
                       <hr>
                       <div class="col-lg-12">
                          <div class="demo-checkbox">

                       <?php foreach($val as $key=>$v){ 
                          $dis_arr = (isset($dis_xsist) && $dis_xsist) ? $dis_xsist : [];
                          $checked = (in_array($v['disease_id'],$dis_arr))? "checked" : "";
                        ?>
                          <input type="checkbox" id="<?= $label."_".$key ?>" class="filled-in chk-col-light-blue" <?= $checked ?> name="disease[]" value="<?= $v['disease_id'] ?>" />
                          <label for="<?= $label."_".$key ?>"><?= ucwords(str_replace("_"," ", $v['name'])) ?></label>		
                   <?php } ?>

                          </div>
                       </div>
                   <?php }
                    ?>

                  <?php
                   $dis_arr = (isset($dis_xsist) && $dis_xsist) ? $dis_xsist : [];
                   $checked = (in_array(0,$dis_arr))? "checked" : "";  
                   $style = ($checked)? "": "display: none;";                 
                  ?>
                    <div class="col-lg-2"></div>
                       <hr>
                       <div class="col-lg-12">
                          <div class="demo-checkbox">                      
                            <input type="checkbox" id="other" class="filled-in chk-col-light-blue" <?= $checked ?> name="disease[]" value="0" />
                            <label for="other">Other</label>		
                          </div>
                          <textarea id="other_text" name="other_text" class="form-control col-lg-4" style="<?= $style ?>" rows="2"><?= (isset($dis_other['other']) && $dis_other['other'])? $dis_other['other']: "" ?></textarea>
                       </div>                  
                 
                </div>
              <div class="pt-20">
                <button type="submit" class="btn btn-success btn-outline">
                  <i class="ti-save-alt"></i> Submit
                </button>
                <button type="reset" class="btn btn-warning btn-outline mr-1">
                  <i class="ti-trash"></i> Reset
                </button>
              </div>
              </form>
            </div>
          </div>
          <!-- /.box -->
          
        </div>
        <!-- /.col-->
      </div>
      <!-- ./row -->
    </section>
    <!-- /.content -->



<input type="hidden" name="base_url" id="base_url" value="<?= Url::base(true) ?>/">


	<!-- popper -->
	<?php $this->registerJsFile('@web/assets/vendor_components/popper/dist/popper.min.js',['depends' => [\yii\web\JqueryAsset::class]]); ?>

	<!-- Bootstrap 4.0-->
	<?php $this->registerJsFile('@web/assets/vendor_components/bootstrap/dist/js/bootstrap.min.js',['depends' => [\yii\web\JqueryAsset::class]]); ?>

	<!-- Superieur Admin for demo purposes -->
	<?php $this->registerJsFile('@web/js/demo.js',['depends' => [\yii\web\JqueryAsset::class]]); ?>

	<!-- CK Editor -->
	<?php //$this->registerJsFile('@web/assets/vendor_components/ckeditor/ckeditor.js',['depends' => [\yii\web\JqueryAsset::class]]); ?>

	<!-- Bootstrap WYSIHTML5 -->
	<?php $this->registerJsFile('@web/assets/vendor_plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.js',['depends' => [\yii\web\JqueryAsset::class]]); ?>

	<!-- Superieur Admin for editor -->
  
  <?php $this->registerJsFile('@web/assets/vendor_components/bootstrap-select/dist/js/bootstrap-select.js',['depends' => [\yii\web\JqueryAsset::class]]); ?>
  <?php $this->registerJsFile('@web/assets/vendor_components/select2/dist/js/select2.full.js',['depends' => [\yii\web\JqueryAsset::class]]); ?>
  <?php $this->registerJsFile('@web/assets/vendor_components/sweetalert/sweetalert.min.js',['depends' => [\yii\web\JqueryAsset::class]]); ?>
  <?php $this->registerJsFile('@web/assets/vendor_components/sweetalert/jquery.sweet-alert.custom.js',['depends' => [\yii\web\JqueryAsset::class]]); ?>
  
	<?php $this->registerJsFile('@web/js/profiling_create.js',['depends' => [\yii\web\JqueryAsset::class]]); ?>

  <script>
    // $(document).ready(()=>{
      // $(document).ready(function(){

      // $(".select2").select2();
      // $('.select2').select2();

    // })
  </script>

frontend/views/profiling/get_employee.php
<?php 
use yii\helpers\Url;
$this->registerCssFile('@web/assets/vendor_components/datatable/datatables.min.css'); 
?>

<div class="row">
    <div class="col-12">
        <div class="box">   
            <div class="box-body">
                <div class="table-responsive">
                    <table id="table_employee" class="datatables table-bordered table-striped table-hover compact">
                    <thead>
                        <tr>
                            <th>PERSON ID</th>
                            <th>NIK</th>
                            <th>NAMA</th>
                            <th>AREA</th>
                            <th>ACTIONS</th>
                        </tr>
                    </thead>
                    </table>
                </div>
            </div>        
        </div>
    </div>
</div>

<?php $this->registerJsFile('@web/assets/vendor_components/datatable/datatables.min.js',['depends' => [\yii\web\JqueryAsset::class]]); ?>

<script>
var table_employee = null;
var base_url_emp = "<?= Url::base(true) ?>/";
$(document).ready(function(){
   
    if(table_employee != null){
	  table_employee.destroy();
	}
	table_employee = $('#table_employee').DataTable( {
	  "processing": true,
	  "serverSide": true,
	  "ajax": {
				"url": base_url_emp + "profiling/listemployee",
				"type": "GET",
	  },
	  "language"     : {
	      "emptyTable"  : "<span class ='label label-danger'>Data not found!</span>",  
	      "infoEmpty"   : "Data Empty",
	      "processing"  : '<div class="loader vertical-align-middle loader-circle"></div>',
	      "search"      : "_INPUT_"
	  },
	  "columns": [	       
	        { "data": "person_id", "width": "5%", "class":"text-center"},
	        { "data": "nik"},
	        { "data": "nama"},
	        { "data": "area"},
	        { 
	          "data": "nik",
	          "width": "20%",
	          "class":"text-center",
	          "render": function (data) {
	          	return `
	          			<button alt="1" class="btn-choice-employee btn btn-info waves-effect waves-l ight btn-xs" title="Click to select ${data}"><i class="fa fa-search"> Choose</i></button>`;
	          }
	        }
	  ],
	  "drawCallback": function( settings, start, end, max, total, pre ) {
            $(".DTFC_LeftBodyLiner").css('overflow','hidden');
	  },
	  "paging":         true,
	  "columnDefs": [
	      {
	      	"targets": [ 1, 3],
	        "orderable": false

	      },
	      {
	          "targets": [ 0],
	          "visible": false
	      }
	  ],
	  "scrollY"          : 520, 
	  "scrollCollapse"   : true,
	  "scrollX"         : false,
      "bAutoWidth" : true

    });

	$('input[type="search"]').attr('placeholder','Search here...').addClass('form-control input-sm m-0');


	$('#table_employee tbody').on( 'click', 'button.btn-choice-employee', function () {
			let data = table_employee.row( $(this).parents('tr') ).data();			
			set_choice(data);			
	})
	
	$('#table_employee tbody').on('dblclick', 'tr', function () {
		var data = table_employee.row( this ).data();
		set_choice(data);
	} );

	function set_choice(data)
	{
		$("#employee_h").val(data.nik);
		$("#name_employee").val(data.nama);
		$("#modal_dialog").modal("hide");
	}

})
</script>

frontend/views/profiling/index.php
<?php 

use yii\helpers\Url;
use yii\web\View;
use common\components\Helper;

?>

	<?php $this->registerCssFile('@web/css/custom.css'); ?>
	<?php $this->registerCssFile('@web/assets/vendor_components/sweetalert/sweetalert.css'); ?>
	<?php $this->registerCssFile('@web/assets/vendor_components/datatable/datatables.min.css'); ?>
	<?php $this->registerCssFile('@web/assets/vendor_components/bootstrap-select/dist/css/bootstrap-select.css'); ?>
	<?php $this->registerCssFile('@web/assets/vendor_components/select2/dist/css/select2.min.css'); ?>

 
  <div class="content-header" style="padding-top:60px !important">
		<div class="d-flex align-items-center">
			<div class="mr-auto">
				<h3 class="page-title"><?= $this->title ?></h3>
				<div class="d-inline-block align-items-center">
					<nav>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="<?= Url::base() . "/home/index" ?>"><i class="mdi mdi-home-outline"></i></a></li>
							<li class="breadcrumb-item active" aria-current="page">List Profiling</li>
						</ol>
					</nav>
				</div>
			</div>
		</div>
	</div>

    <!-- Main content -->
    <section class="content p-20">
      <div class="container">
      <div class="row">
        <div class="col-12">

         <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">List Profiling</h3>
              <button id="btn-create-profiling" class="btn btn-success waves-effect waves-light pull-right w-150" title="Click to create"><i class="fa fa-plus"></i> Create</button>
            </div>
            <!-- /.box-header -->
            <div class="box-body">

			<!-- <div class="row">
				<div class="col-lg-12">
					sasasas
				</div>
			</div> -->

			<!-- <form class="form-horizontal"> -->
			<form role="form" id="formFilterProfiling">
              <div class="box-body">	
				<div class="row">
					<div class="col-md-3 col-12">
					<div class="form-group">
						<label>NIK</label>
							<input type="text" class="form-control opt-filter" id="nik" name="nik" value="" placeholder="NIK">
					</div>				
					</div>
					
					<div class="col-md-3 col-12">
					<div class="form-group">
						<label>Name</label>
							<input type="text" class="form-control opt-filter" name="nama" placeholder="Name">
					</div>				 
					</div>
					
					<div class="col-md-3 col-12">
					<div class="form-group">
						<label>Title</label>
							<input type="text" class="form-control opt-filter" name="title" placeholder="Title">
					</div>				
					</div>

					<div class="col-md-3 col-12">
					<div class="form-group">
						<label>Organization</label>
							<input type="text" class="form-control opt-filter" name="organization" placeholder="Organization">
					</div>				
					</div>
					
					<div class="col-md-3 col-12">
					<div class="form-group">
						<label>Department</label>
							<input type="text" class="form-control opt-filter" name="department" placeholder="department">
					</div>				
					</div>	

					<div class="col-md-3 col-12">
					<div class="form-group">
						<label>Division</label>
							<input type="text" class="form-control opt-filter" name="division" placeholder="division">
					</div>				
					</div>

					<div class="col-md-3 col-12">
					<div class="form-group">
						<label>Area</label>
							<input type="text" class="form-control opt-filter" name="area" placeholder="area">
					</div>				
					</div>	
					
					<div class="col-md-3 col-12">
					<div class="form-group">
						<label>Job</label>
							<input type="text" class="form-control opt-filter" name="job" placeholder="job">
					</div>				
					</div>	
					
					<div class="col-md-3 col-12">
					<div class="form-group">
						<label>Job Category</label>
							<input type="text" class="form-control opt-filter" name="job_category" placeholder="Job Category">
					</div>				
					</div>	
					
					<div class="col-md-3 col-12">
						<div class="form-group">
							<label>Profiling</label>
								<input type="text" class="form-control opt-filter" name="profiling_disease" placeholder="Profiling">
						</div>				
					</div>		
							
			
			  	</div>

				<div class="row">
				<div class="col-md-3 col-12">
					<div class="form-group">
						<label></label>
						<button type="button" id="btn_search" class="btn btn-info btn-sm">Search</button>
						<button type="button" id="btn_export" class="btn btn-warning btn-sm">Export</button>
						<button type="button" id="btn_reset" class="btn btn-default btn-sm">Reset</button>
					</div>				
					</div>	
				</div>

              </div>
    
            </form>

							<div class="table-responsive">
							  <table id="table_profiling" class="datatables table-bordered table-striped table-hover display compact">
								<thead>
									<tr>
										<th>ID</th>
										<th>Actions</th>
										<th>NIK</th>
										<th>Name</th>
										<th>Profiling</th>
										<th>Title</th>
										<th>Organization</th>
										<th>Department</th>
										<th>Division</th>
										<th>Job</th>
										<th>Job Category</th>
										<th>Area</th>
										<th>Directorate</th>
										<th>Employee_category</th>
										<th>Email</th>									
										
									</tr>
								</thead>
							  </table>
							</div>
            </div>
            <!-- /.box-body -->
          </div>

          
        </div>
        <!-- /.col-->
      </div>
      </div>
      <!-- ./row -->
    </section>
    <!-- /.content -->



<input type="hidden" name="base_url" id="base_url" value="<?= Url::base(true) ?>/">


  <!-- Datatables -->
	<?php $this->registerJsFile('@web/assets/vendor_components/datatable/datatables.min.js',['depends' => [\yii\web\JqueryAsset::class]]); ?>
	<!-- popper -->
	<?php $this->registerJsFile('@web/assets/vendor_components/popper/dist/popper.min.js',['depends' => [\yii\web\JqueryAsset::class]]); ?>

	<!-- Bootstrap 4.0-->
	<?php $this->registerJsFile('@web/assets/vendor_components/bootstrap/dist/js/bootstrap.min.js',['depends' => [\yii\web\JqueryAsset::class]]); ?>

	<!-- Sweet-Alert  -->
	<?php $this->registerJsFile('@web/assets/vendor_components/sweetalert/sweetalert.min.js',['depends' => [\yii\web\JqueryAsset::class]]); ?>
	<?php $this->registerJsFile('@web/assets/vendor_components/sweetalert/jquery.sweet-alert.custom.js',['depends' => [\yii\web\JqueryAsset::class]]); ?>

	<?php $this->registerJsFile('@web/assets/vendor_components/bootstrap-select/dist/js/bootstrap-select.js',['depends' => [\yii\web\JqueryAsset::class]]); ?>
    <?php $this->registerJsFile('@web/assets/vendor_components/select2/dist/js/select2.full.js',['depends' => [\yii\web\JqueryAsset::class]]); ?>

	<?php $this->registerJsFile('@web/js/profiling_index.js',['depends' => [\yii\web\JqueryAsset::class]]); ?>